stage_name: 'eval_dyadic'
freeze_gaze_backbone: true
num_epochs: 1
save_every: 1

weights:
  heatmap: 1
  inout: 1
  pattern: 1

# dataset details
batch_size: 32
num_workers: 8
pin_memory: true
prefetch_factor: 1
persistent_workers: true

dataset_name: "dyadic"
pattern_type: 'multi_class' 
save_best_metrics: "pattern_Acc" #Options: AUC, pattern_Acc, l2_dist
