stage_name: 'finetune_gazefollow'
freeze_gaze_backbone: false
num_epochs: 10
save_every: 1

optimizer:
  lr: 1e-5
  weight_decay: 0
  warm_up_epochs: 0
weights:
  heatmap: 1000.0
  inout: 1.0
  pattern: 0

# dataset details
batch_size: 32
num_workers: 8
pin_memory: true
prefetch_factor: 1
persistent_workers: true

dataset_name: "gazefollow" 
pattern_type: 'multi_class' 
save_best_only: false
save_best_metrics: "AUC" #Options: AUC, pattern_Acc, l2_dist
