stage_name: 'finetune_gp_static'
freeze_gaze_backbone: true
num_epochs: 10
save_every: 1

optimizer:
  lr: 2.5e-4
  weight_decay: 0
  warm_up_epochs: 0
weights:
  heatmap: 0
  inout: 0
  pattern: 10

# dataset details
batch_size: 32
num_workers: 8
pin_memory: true
prefetch_factor: 1
persistent_workers: true

dataset_name: "gp_static" 
pattern_type: 'multi_class' 
save_best_only: false
save_best_metrics: "pattern_Acc" #Options: AUC, l2_dist, pattern_Acc, pattern_AP, pattern_AUC
